using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityGameFramework.Runtime;
namespace MetaClient
{
    public class FinchFaceButton : MonoBehaviour
    {
        //[Header("当前选择层级")]
        //public EFinchFaceCengJi eFinchFaceCengJi = EFinchFaceCengJi.None;//默认为未开始选择层级
        //[Header("当前界面分支")]
        //public EFinchFaceStyple eFinchFaceStyple = EFinchFaceStyple.None;//默认为未选择界面分支
        //[Header("链接的Ui脚本")]
        //public FinchFaceForm finchFaceForm;//默认为未选择界面分支
        //[Header("是否改变当前的层级")]
        //public bool changeCengJi = false;
        //// Start is called before the first frame update
        //void Awake()
        //{
        //    Button btn = this.GetComponent<Button>();
        //    btn.onClick.AddListener(OnClick);
        //}
        //private void OnClick()
        //{
        //    finchFaceForm.ChooseJieMianFun(eFinchFaceStyple,eFinchFaceCengJi,changeCengJi,this.gameObject.name);
        //    //Debug.Log("Button Clicked. ClickHandler.");
        //}
        //// Update is called once per frame
        ////void Update()
        ////{

        ////}
    }
}
