using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace MetaClient
{
    public class CustomRoleListCell : MonoBehaviour
    {
        public Text Message;
        private DRCustomBody bodyData;
        private CustomRoleForm form;

        public void Init(DRCustomBody _data,CustomRoleForm _form)
        {
            bodyData = _data;
            form = _form;
            Message.text = bodyData.Name;

            var btn = GetComponent<Button>();
            btn.onClick.AddListener(() => 
            {
                form.ClickListCell(bodyData);
            });
        }
    }
}