using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
namespace MetaClient
{

    public class UICustomDrag : MonoBehaviour, IDragHandler, IEndDragHandler, IBeginDragHandler
    {
        // Start is called before the first frame update
        void Start()
        {

        }
        public void OnDrag(PointerEventData eventData)
        {
            //CustomManager.Instance
            Debug.Log(eventData.delta.x + "");
        }
        public void OnBeginDrag(PointerEventData eventData)
        {
        }
        public void OnEndDrag(PointerEventData eventData)
        {
            
        }
        // Update is called once per frame
        void Update()
        {

        }
    }
}
